### ISSUE TITLE
As a user I should be able to see the organization / user owned by a repo

### ISSUE THREAD

**Issue by thescientist13** [thescientist13/github-dashboard#105]
This would help add distinction between upstream and forks.  It could simply be prefixing the repo name with the organization, eg. _some-organization/this-repo_

**Comment by thescientist13** [comment]
linked incorrectly by accident

**Comment by jpoo90** [comment]
This would be really helpful. To avoid situations like this one :joy: 
<img width="391" alt="screen shot 2017-04-25 at 1 41 40 pm" src="https://cloud.githubusercontent.com/assets/5958030/25399389/4688e21a-29bd-11e7-92db-7215b9d920b6.png">. It might be

**Comment by thescientist13** [comment]
oh wow, lol 

yeah... definitely agree.  I believe it is lined up for this sprint some definitely open to contributions for this (should be pretty simple) or I'll probably be able to get to it in the next week or so.

**Comment by thescientist13** [comment]
Assigning this to myself to
1. Update the product image to show off this new feature used in the README
1. Update the Product Overview wiki

**Comment by thescientist13** [comment]
updated the product overview and the image in the README
https://github.com/thescientist13/github-dashboard/wiki/Product-Overview#following--personal-repos
