### ISSUE TITLE
refreshing a served app shows a 404 (yarn run serve)

### ISSUE THREAD

**Issue by kbuechner** [thescientist13/github-dashboard#126]

**Comment by thescientist13** [comment]
My understanding from talking to the author is that this occurs when running 
`yarn run serve`

and refreshing the page.  There is no fallback to _index.html_ when the URL has a route loaded, eg. _/following/_ or _/personal/_
<img width="575" alt="404" src="https://cloud.githubusercontent.com/assets/895923/23827226/afc51d34-067c-11e7-88b5-61dbf4993814.png">

**Comment by thescientist13** [comment]
likely a side effect of #92

**Comment by thescientist13** [comment]
would need to be some sort of "fallback" arg / option passed to `http-server`
https://www.npmjs.com/package/http-server

when run as part of `yarn run serve`
