### ISSUE TITLE
terminal console warning: updated reference to ReactTestUtils to be react-dom/test-utils

### ISSUE THREAD

**Issue by thescientist13** [thescientist13/github-dashboard#151]
```bash
$ yarn run test
  console.error node_modules/fbjs/lib/warning.js:36
    Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
```

**Comment by jpoo90** [comment]
@thescientist13 Did you find a case were enzyme was not able to replace `test-utils`? 

Since we are using enzyme, I think we can remove the dependency on `test-utils`. Let me know your thoughts.

**Comment by thescientist13** [comment]
@jpoo90 
I haven't looked, but that sounds like the right way to go to me.

**Comment by jpoo90** [comment]
@thescientist13 

Update:

1.  I was wrong about removing `test-utils`, Enzyme [requires it to work](http://airbnb.io/enzyme/docs/installation/index.html#working-with-react-15). 

2. There's been [a lot going on](https://github.com/airbnb/enzyme/pull/876) about these warning messages. Latest `enzyme` and `React` changed some dependencies. Reading on it to see what needs to be changed on this project.

**Comment by thescientist13** [comment]
Thanks for reviewing @jpoo90 !

**Comment by jpoo90** [comment]
@thescientist13 
I did this:

1.  `yarn upgrade react react-dom enzyme react-test-renderer` 

1.  Moved `react-addons-test-utils` to the devDependencies and upgraded it. 

After this the test utils warnings disappear, but now we got:

```bash
 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

 RouterContext: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
```

We are not using PropTypes nor React.createClass in the project, but React generates the warnings if any dependency in the entire tree references a deprecated property. 

We'll need to keep an eye on releases on the dependencies. Let me know if you want me to open a PR with these updates,

**Comment by thescientist13** [comment]
seems like the upgrades in #156 has removed this error!  🎉 

Will close this when #157 gets merged.
