### ISSUE TITLE
implement a state / data management architecture pattern (flux, mobx, etc)

### ISSUE THREAD

**Issue by thescientist13** [thescientist13/github-dashboard#38]
or something that follows the reactive paradigm
https://github.com/mobxjs/mobx

**Comment by thescientist13** [comment]
That said, would an observable pattern be more appropriate?  For issues / PRs on busy repos, real time updates would be an interesting feature to add

**Comment by thescientist13** [comment]
A new contented enters the scene
https://github.com/windsockjs/windsock

**Comment by thescientist13** [comment]
use immutable.js?
https://facebook.github.io/immutable-js/

**Comment by thescientist13** [comment]
TODO
- immutable.js
- map errors (race conditions with state?)

**Comment by obuckley-kenzan** [comment]
https://github.com/evgenyrodionov/redux-logger

**Comment by obuckley-kenzan** [comment]
A potential tool to consider
https://github.com/evgenyrodionov/redux-logger

**Comment by thescientist13** [comment]
Other good links
- http://redux.js.org/docs/basics/UsageWithReact.html
- https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.ju2ezwggc
- https://facebook.github.io/react/docs/thinking-in-react.html
