### ISSUE TITLE
Modify API request to return more than 30 repos. 

### ISSUE THREAD

**Issue by cxoltero** [thescientist13/github-dashboard#63]
As of now, when submitting request, github returns and array with a max of 30 items. 
enhancement should return all of them with pagination.
Should discuss how many items per page. 
current call https://api.github.com/users/user/repos

proposed call `https://api.github.com/user/repos?page=5&per_page=50`

**Comment by thescientist13** [comment]
@cxoltero I can reproduce this as well but I am seeing the `Link` headers as shown in the API docs you linked.  So, will need to implement some pagination functionality.

**Comment by thescientist13** [comment]
An infinite scroll solution might be nice here
